apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibliotheque-api-gateway
  namespace: bibliotheque
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bibliotheque-api-gateway
  template:
    metadata:
      labels:
        app: bibliotheque-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ${DOCKER_REGISTRY}/bibliotheque-api-gateway:${TAG}
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bibliotheque-secrets
              key: jwt-secret
        - name: AUTH_SERVICE_URL
          value: "http://bibliotheque-auth-service:3002"
        - name: BOOKS_SERVICE_URL
          value: "http://bibliotheque-books-service:3003"
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: "0.3"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 15
